# Generated by Django 3.1.4 on 2020-12-28 12:59

import cloudinary.models
from django.db import migrations
import search.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='in_shot_encoding',
            field=search.fields.NumpyArrayField(default=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='in_shot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='search_shot'),
        ),
    ]
